### ISSUE TITLE
KVM requires a CPU that supports vmx or svm  accel

### ISSUE THREAD

**Issue by criquil** [docker-android-sdk/android-29#1]
ERROR: resizing partition e2fsck failed with exit code 8
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

is it an issue or is it just me with a setting issue?

**Comment by ppoffice** [comment]
@criquil You need to install KVM on your host machine.

**Comment by criquil** [comment]
Thanks for the tip....unexperienced so far...my bad
